apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: multitool
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool
